('localhost', 'localhost', 'RevolucioBot', BotPassword('Revolucio', 'REMOVED'))
('fr', 'vikidia', 'RevolucioBot', BotPassword('Revolucio', 'REMOVED'))
('en', 'vikidia', 'RevolucioBot', BotPassword('Revolucio', 'REMOVED'))
('dicoado', 'dicoado', 'RevolucioBot', BotPassword('Revolucio', 'REMOVED'))
('fr', 'wikipedia', 'RevolucioBot', BotPassword('RevolucioBot', 'REMOVED'))
